/*
 * Qlocktwo_Drivers_Config.h
 *
 *  Created on: 10.04.2016
 *      Author: Jean-Martin George
 */

#ifndef QLOCKTWO_DRIVERS_CONFIG_H_
#define QLOCKTWO_DRIVERS_CONFIG_H_


#include "Drivers_Config_Def.h"
#include "Main_Config.h"

#if (PROJECT == PROJECT__QLOCKTWO)

#if (	(QLOCKTWO_REVISION == QLOCKTWO_REVISION_2)\
	||	(QLOCKTWO_REVISION == QLOCKTWO_REVISION_3)\
	)
/* WS2801 */
#define LEDS_NB					114
#define RGB_LED_ORDER			RGB_LED_ORDER__CONFIGURABLE
#define LED_ORDER				LED_ORDER_TOP_LEFT_LEFT
#endif

#if (QLOCKTWO_REVISION == QLOCKTWO_REVISION_4)
/* WS2812 */
#define LEDS_NB					114
#define WS2812_CONNECTION_TYPE	WS2812_CONNECTION_TYPE_DIGIDOT_SPI
#define WS2812_DIGIDOT_CS_DDR	DDRB
#define WS2812_DIGIDOT_CS_PORT	PORTB
#define WS2812_DIGIDOT_CS_PIN	PB0
#define RGB_LED_ORDER			RGB_LED_ORDER__CONFIGURABLE
#define LED_ORDER				LED_ORDER_BOTTOM_LEFT_RIGHT
#endif

/* DCF77 */
#define DCF77_DATA_DDR			DDRC
#define DCF77_DATA_PORT			PINC
#define DCF77_DATA_PIN			PC1
#define DCF77_TASK_TIME			100

/* CTL LED */
#define UC_LED_DDR				DDRD
#define UC_LED_PORT				PORTD
#define UC_LED_PIN				PD4
#define CLOCK_LED_DDR			DDRD
#define CLOCK_LED_PORT			PORTD
#define CLOCK_LED_PIN			PD5
#define TEST1_LED_DDR			DDRD
#define TEST1_LED_PORT			PORTD
#define TEST1_LED_PIN			PD6
#define TEST2_LED_DDR			DDRD
#define TEST2_LED_PORT			PORTD
#define TEST2_LED_PIN			PD7
#define TEST3_LED_DDR			DDRD
#define TEST3_LED_PORT			PORTD
#define TEST3_LED_PIN			PD3
#define DCF77_LED_DDR			TEST1_LED_DDR
#define DCF77_LED_PORT			TEST1_LED_PORT
#define DCF77_LED_PIN			TEST1_LED_PIN
#define IRMP_LED_DDR			TEST2_LED_DDR
#define IRMP_LED_PORT			TEST2_LED_PORT
#define IRMP_LED_PIN			TEST2_LED_PIN
#define RUNTIME_LED_DDR 		TEST2_LED_DDR
#define RUNTIME_LED_PORT 		TEST2_LED_PORT
#define RUNTIME_LED_PIN			TEST2_LED_PIN
#define RUNTIME_OSC_DDR 		TEST3_LED_DDR
#define RUNTIME_OSC_PORT 		TEST3_LED_PORT
#define RUNTIME_OSC_PIN			TEST3_LED_PIN

/* USART */
#define USART_DATA_LENGTH_READ_MAX	0

/* LDR */
#define LDR_ADC_PIN		0

#if (	(QLOCKTWO_REVISION == QLOCKTWO_REVISION_3)\
	||	QLOCKTWO_REVISION == QLOCKTWO_REVISION_4)\
/* IRMP */
#define IRMP_REMOTE_ADDRESS		0xF708
#define IRMP_BUTTON_OFF			0x001B
#define IRMP_BUTTON_MODE		0x0004
#define IRMP_BUTTON_FUNC1		0x001F
#define IRMP_BUTTON_FUNC2		0x001E
#define IRMP_BUTTON_FUNC3		0x001A
#define IRMP_BUTTON_UP			0x0005
#define IRMP_BUTTON_DOWN		0x0000
#define IRMP_BUTTON_LEFT		0x0008
#define IRMP_BUTTON_RIGHT		0x0001
#endif

#if (QLOCKTWO_REVISION == QLOCKTWO_REVISION_2)
/* 74HC165 */
#define HC165_CLK_DDR	DDRB
#define HC165_CLK_PORT	PORTB
#define HC165_CLK_PIN	PB3
#define HC165_SL_DDR	DDRB
#define HC165_SL_PORT	PORTB
#define HC165_SL_PIN	PB2
#define HC165_OUT_DDR	DDRB
#define HC165_OUT_PORT	PINB
#define HC165_OUT_PIN	PB1
#endif

#endif


#endif /* QLOCKTWO_DRIVERS_CONFIG_H_ */
