/*
 * Drivers_Config.h
 *
 *  Created on: 26.01.2013
 *      Author: Jean-Martin George
 */

#ifndef DRIVERS_CONFIG_H_
#define DRIVERS_CONFIG_H_

#include "Main_Config.h"


#if (PROJECT == PROJECT__TEMPERATURE_LOGGER)

/*********** CTL LED ***********/
#define UC_LED_DDR		DDRD
#define UC_LED_PORT		PORTD
#define UC_LED_PIN		PD5
#define CLOCK_LED_DDR	DDRD
#define CLOCK_LED_PORT	PORTD
#define CLOCK_LED_PIN	PD6
#define TEST1_LED_DDR	DDRD
#define TEST1_LED_PORT	PORTD
#define TEST1_LED_PIN	PD7


/********* BUTTONS ********/
#define BUTTON_OFF_DDR		DDRC
#define BUTTON_OFF_PORT		PINC
#define BUTTON_OFF_PIN		BUTTON_INVALID
#define BUTTON_MODE_DDR		DDRC
#define BUTTON_MODE_PORT	PINC
#define BUTTON_MODE_PIN		PC2
#define BUTTON_FUNC1_DDR	DDRC
#define BUTTON_FUNC1_PORT	PINC
#define BUTTON_FUNC1_PIN	BUTTON_INVALID
#define BUTTON_FUNC2_DDR	DDRC
#define BUTTON_FUNC2_PORT	PINC
#define BUTTON_FUNC2_PIN	PC4
#define BUTTON_FUNC3_DDR	DDRC
#define BUTTON_FUNC3_PORT	PINC
#define BUTTON_FUNC3_PIN	BUTTON_INVALID
#define BUTTON_LEFT_DDR		DDRC
#define BUTTON_LEFT_PORT	PINC
#define BUTTON_LEFT_PIN		BUTTON_INVALID
#define BUTTON_RIGHT_DDR	DDRC
#define BUTTON_RIGHT_PORT	PINC
#define BUTTON_RIGHT_PIN	BUTTON_INVALID
#define BUTTON_UP_DDR		DDRC
#define BUTTON_UP_PORT		PINC
#define BUTTON_UP_PIN		BUTTON_INVALID
#define BUTTON_DOWN_DDR		DDRC
#define BUTTON_DOWN_PORT	PINC
#define BUTTON_DOWN_PIN		BUTTON_INVALID


/********** USART *********/
#define USART_REQESTER_TRANSFER				0x10
#define USART_DATA_LENGTH_TRANSFER_READ		1
#define USART_DATA_LENGTH_TRANSFER_WRITE	20

#define USART_DATA_LENGTH_READ_MAX			10


/*********** LCD **********/
#define LCD_RS_DDR					DDRB
#define LCD_RS_PORT					PORTB
#define LCD_RS_PIN					PB0

#define LCD_RW_DDR					DDRB
#define LCD_RW_PORT					PORTB
#define LCD_RW_PIN					PB1

#define LCD_E_DDR					DDRB
#define LCD_E_PORT					PORTB
#define LCD_E_PIN					PB2

#define LCD_DB_DDR					DDRA
#define LCD_DB_PORT					PORTA
#define LCD_DB0_PIN					PA0
#define LCD_DB1_PIN					PA1
#define LCD_DB2_PIN					PA2
#define LCD_DB3_PIN					PA3
#define LCD_DB4_PIN					PA4
#define LCD_DB5_PIN					PA5
#define LCD_DB6_PIN					PA6
#define LCD_DB7_PIN					PA7


/*********** DS18B20 **********/
#define DS18B20_DATA_DDR			DDRC
#define DS18B20_DATA_PORT			PORTC
#define DS18B20_DATA_PINR			PINC
#define DS18B20_DATA_PIN			PC5

#define DS18B20_ALARM_TLOW			0	/* not supported for now */
#define DS18B20_ALARM_THIGH			0	/* not supported for now */

/* SPI not needed but speed has to be defined */
#define SPI_SPEED SPI_CLK_DIV_8

#endif


#if (PROJECT == PROJECT__QLOCKTWO)
#ifdef __AVR_ATmega644P__ /* Qlocktwo 2.x / 3.0 */

/*********** WS2801 ***********/
#define WS2801_NB							114
#define RGB_LED_CONNECTION__RED_GREEN_BLUE	1
#define RGB_LED_CONNECTION__BLUE_GREEN_RED	2
#define RGB_LED_CONNECTION					RGB_LED_CONNECTION__RED_GREEN_BLUE

/********** DCF77 ***************/
#define DCF77_DATA_DDR		DDRB
#define DCF77_DATA_PORT		PINB
#define DCF77_DATA_PIN		PB0
#define DCF77_TASK_TIME		100

/*********** CTL LED ***********/
#define UC_LED_DDR			DDRD
#define UC_LED_PORT			PORTD
#define UC_LED_PIN			PD4
#define CLOCK_LED_DDR		DDRD
#define CLOCK_LED_PORT		PORTD
#define CLOCK_LED_PIN		PD5
#define TEST1_LED_DDR		DDRD
#define TEST1_LED_PORT		PORTD
#define TEST1_LED_PIN		PD6
#define TEST2_LED_DDR		DDRD
#define TEST2_LED_PORT		PORTD
#define TEST2_LED_PIN		PD7
#define TEST3_LED_DDR		DDRA
#define TEST3_LED_PORT		PORTA
#define TEST3_LED_PIN		PA7
#define DCF77_LED_DDR		TEST1_LED_DDR
#define DCF77_LED_PORT		TEST1_LED_PORT
#define DCF77_LED_PIN		TEST1_LED_PIN
#define IRMP_LED_DDR		TEST2_LED_DDR
#define IRMP_LED_PORT		TEST2_LED_PORT
#define IRMP_LED_PIN		TEST2_LED_PIN
#define RUNTIME_LED_DDR 	TEST2_LED_DDR
#define RUNTIME_LED_PORT 	TEST2_LED_PORT
#define RUNTIME_LED_PIN		TEST2_LED_PIN
#define RUNTIME_OSC_DDR 	TEST3_LED_DDR
#define RUNTIME_OSC_PORT 	TEST3_LED_PORT
#define RUNTIME_OSC_PIN		TEST3_LED_PIN

/********* BUTTONS ********/
#define BUTTON_OFF_DDR		DDRB
#define BUTTON_OFF_PORT		PINB
#define BUTTON_OFF_PIN		BUTTON_INVALID
#define BUTTON_MODE_DDR		DDRB
#define BUTTON_MODE_PORT	PINB
#define BUTTON_MODE_PIN		PB1
#define BUTTON_FUNC1_DDR	DDRB
#define BUTTON_FUNC1_PORT	PINB
#define BUTTON_FUNC1_PIN	PB2
#define BUTTON_FUNC2_DDR	DDRB
#define BUTTON_FUNC2_PORT	PINB
#define BUTTON_FUNC2_PIN	PB3
#define BUTTON_FUNC3_DDR	DDRB
#define BUTTON_FUNC3_PORT	PINB
#define BUTTON_FUNC3_PIN	BUTTON_INVALID
#define BUTTON_LEFT_DDR		DDRB
#define BUTTON_LEFT_PORT	PINB
#define BUTTON_LEFT_PIN		BUTTON_INVALID
#define BUTTON_RIGHT_DDR	DDRB
#define BUTTON_RIGHT_PORT	PINB
#define BUTTON_RIGHT_PIN	BUTTON_INVALID
#define BUTTON_UP_DDR		DDRB
#define BUTTON_UP_PORT		PINB
#define BUTTON_UP_PIN		BUTTON_INVALID
#define BUTTON_DOWN_DDR		DDRB
#define BUTTON_DOWN_PORT	PINB
#define BUTTON_DOWN_PIN		BUTTON_INVALID

/********** USART *********/
#define USART_DATA_LENGTH_READ_MAX	0

/********** IRMP **********/
#define IRMP_REMOTE_ADDRESS		0xF708
#define IRMP_BUTTON_OFF			0x001B
#define IRMP_BUTTON_MODE		0x0004
#define IRMP_BUTTON_FUNC1		0x001F
#define IRMP_BUTTON_FUNC2		0x001E
#define IRMP_BUTTON_FUNC3		0x001A
#define IRMP_BUTTON_UP			0x0005
#define IRMP_BUTTON_DOWN		0x0000
#define IRMP_BUTTON_LEFT		0x0008
#define IRMP_BUTTON_RIGHT		0x0001

/********* 74HC165 ********/
#define HC165_CLK_DDR	DDRB
#define HC165_CLK_PORT	PORTB
#define HC165_CLK_PIN	PB3
#define HC165_SL_DDR	DDRB
#define HC165_SL_PORT	PORTB
#define HC165_SL_PIN	PB2
#define HC165_OUT_DDR	DDRB
#define HC165_OUT_PORT	PINB
#define HC165_OUT_PIN	PB1

/*********** LDR ***********/
#define LDR_ADC_PIN		0

#endif
#endif


#if (PROJECT == PROJECT__QLOCKTWO)
#ifdef __AVR_ATmega328P__ /* Qlocktwo 4.0 */

/*********** WS2801 ***********/
#define WS2812_NB							114
#define RGB_LED_CONNECTION__RED_GREEN_BLUE	1
#define RGB_LED_CONNECTION__BLUE_GREEN_RED	2
#define RGB_LED_CONNECTION					RGB_LED_CONNECTION__BLUE_GREEN_RED

/********** DCF77 ***************/
#define DCF77_DATA_DDR		DDRB
#define DCF77_DATA_PORT		PINB
#define DCF77_DATA_PIN		PB0
#define DCF77_TASK_TIME		100

/*********** CTL LED ***********/
#define UC_LED_DDR			DDRD
#define UC_LED_PORT			PORTD
#define UC_LED_PIN			PD4
#define CLOCK_LED_DDR		DDRD
#define CLOCK_LED_PORT		PORTD
#define CLOCK_LED_PIN		PD5
#define TEST1_LED_DDR		DDRD
#define TEST1_LED_PORT		PORTD
#define TEST1_LED_PIN		PD6
#define TEST2_LED_DDR		DDRD
#define TEST2_LED_PORT		PORTD
#define TEST2_LED_PIN		PD7
#define TEST3_LED_DDR		DDRD
#define TEST3_LED_PORT		PORTD
#define TEST3_LED_PIN		PD3
#define DCF77_LED_DDR		TEST1_LED_DDR
#define DCF77_LED_PORT		TEST1_LED_PORT
#define DCF77_LED_PIN		TEST1_LED_PIN
#define IRMP_LED_DDR		TEST2_LED_DDR
#define IRMP_LED_PORT		TEST2_LED_PORT
#define IRMP_LED_PIN		TEST2_LED_PIN
#define RUNTIME_LED_DDR 	TEST2_LED_DDR
#define RUNTIME_LED_PORT 	TEST2_LED_PORT
#define RUNTIME_LED_PIN		TEST2_LED_PIN
#define RUNTIME_OSC_DDR 	TEST3_LED_DDR
#define RUNTIME_OSC_PORT 	TEST3_LED_PORT
#define RUNTIME_OSC_PIN		TEST3_LED_PIN

/********** USART *********/
#define USART_DATA_LENGTH_READ_MAX	0

/********** IRMP **********/
#define IRMP_REMOTE_ADDRESS		0xF708
#define IRMP_BUTTON_OFF			0x001B
#define IRMP_BUTTON_MODE		0x0004
#define IRMP_BUTTON_FUNC1		0x001F
#define IRMP_BUTTON_FUNC2		0x001E
#define IRMP_BUTTON_FUNC3		0x001A
#define IRMP_BUTTON_UP			0x0005
#define IRMP_BUTTON_DOWN		0x0000
#define IRMP_BUTTON_LEFT		0x0008
#define IRMP_BUTTON_RIGHT		0x0001


/*********** LDR ***********/
#define LDR_ADC_PIN		0

/* SPI not needed but speed has to be defined */
#define SPI_SPEED SPI_DISABLED

#endif
#endif


#if (PROJECT == PROJECT__IRMP)

/*********** CTL LED ***********/
//#define UC_LED_DDR			DDRB
//#define UC_LED_PORT			PORTB
//#define UC_LED_PIN			PB1
//#define IRMP_LED_DDR			UC_LED_DDR
//#define IRMP_LED_PORT			UC_LED_PORT
//#define IRMP_LED_PIN			UC_LED_PIN

/********** USART *********/
#define USART_DATA_LENGTH_READ_MAX	0

/********** IRMP **********/
#define IRMP_REMOTE_ADDRESS		0xF708
#define IRMP_BUTTON_OFF			0x001B
#define IRMP_BUTTON_MODE		0x0004
#define IRMP_BUTTON_FUNC1		0x001F
#define IRMP_BUTTON_FUNC2		0x001E
#define IRMP_BUTTON_FUNC3		0x001A
#define IRMP_BUTTON_UP			0x0005
#define IRMP_BUTTON_DOWN		0x0000
#define IRMP_BUTTON_LEFT		0x0008
#define IRMP_BUTTON_RIGHT		0x0001

/* SPI not needed but speed has to be defined */
#define SPI_SPEED SPI_DISABLED

#endif


#if (PROJECT == PROJECT__LED_TABLE)

/*********** WS2801 ***********/
#define WS2801_NB		(LED_MATRIX_SIZE_COL * LED_MATRIX_SIZE_LIN)
#define RGB_LED_CONNECTION__RED_GREEN_BLUE	1
#define RGB_LED_CONNECTION__BLUE_GREEN_RED	2
#define RGB_LED_CONNECTION					RGB_LED_CONNECTION__BLUE_GREEN_RED

/********** DCF77 ***************/
#define DCF77_DATA_DDR		DDRB
#define DCF77_DATA_PORT		PINB
#define DCF77_DATA_PIN		PB0
#define DCF77_TASK_TIME		100

/*********** CTL LED ***********/
#define UC_LED_DDR			DDRD
#define UC_LED_PORT			PORTD
#define UC_LED_PIN			PD4
#define CLOCK_LED_DDR		DDRD
#define CLOCK_LED_PORT		PORTD
#define CLOCK_LED_PIN		PD5
#define TEST1_LED_DDR		DDRD
#define TEST1_LED_PORT		PORTD
#define TEST1_LED_PIN		PD6
#define TEST2_LED_DDR		DDRD
#define TEST2_LED_PORT		PORTD
#define TEST2_LED_PIN		PD7
#define TEST3_LED_DDR		DDRA
#define TEST3_LED_PORT		PORTA
#define TEST3_LED_PIN		PA7
#define DCF77_LED_DDR		TEST1_LED_DDR
#define DCF77_LED_PORT		TEST1_LED_PORT
#define DCF77_LED_PIN		TEST1_LED_PIN
#define IRMP_LED_DDR		TEST2_LED_DDR
#define IRMP_LED_PORT		TEST2_LED_PORT
#define IRMP_LED_PIN		TEST2_LED_PIN
#define RUNTIME_LED_DDR 	TEST2_LED_DDR
#define RUNTIME_LED_PORT 	TEST2_LED_PORT
#define RUNTIME_LED_PIN		TEST2_LED_PIN
#define RUNTIME_OSC_DDR 	TEST3_LED_DDR
#define RUNTIME_OSC_PORT 	TEST3_LED_PORT
#define RUNTIME_OSC_PIN		TEST3_LED_PIN


/********* 74HC165 ********/
#define HC165_CLK_DDR	DDRB
#define HC165_CLK_PORT	PORTB
#define HC165_CLK_PIN	PB3
#define HC165_SL_DDR	DDRB
#define HC165_SL_PORT	PORTB
#define HC165_SL_PIN	PB2
#define HC165_OUT_DDR	DDRB
#define HC165_OUT_PORT	PINB
#define HC165_OUT_PIN	PB1


/********** USART *********/

#define USART_REQESTER_MODE			0x40
#define USART_REQESTER_BUTTON		0x30
#define USART_REQESTER_COLOR		0x10
#define USART_REQESTER_CLOCK		0x80

#define USART_DATA_LENGTH_MODE		1
#define USART_DATA_LENGTH_BUTTON	2
#define USART_DATA_LENGTH_COLOR		4
#define USART_DATA_LENGTH_CLOCK		8
#define USART_DATA_LENGTH_READ_MAX	4


/********** IRMP **********/
#define IRMP_REMOTE_ADDRESS		0xF708
#define IRMP_BUTTON_OFF			0x001B
#define IRMP_BUTTON_MODE		0x0004
#define IRMP_BUTTON_FUNC1		0x001F
#define IRMP_BUTTON_FUNC2		0x001E
#define IRMP_BUTTON_FUNC3		0x001A
#define IRMP_BUTTON_UP			0x0005
#define IRMP_BUTTON_DOWN		0x0000
#define IRMP_BUTTON_LEFT		0x0008
#define IRMP_BUTTON_RIGHT		0x0001

#endif


#if (PROJECT == PROJECT__LED_MIRROR)

/*********** WS2801 ***********/
#define WS2801_NB		(LED_MATRIX_SIZE_COL * LED_MATRIX_SIZE_LIN)
#define RGB_LED_CONNECTION__RED_GREEN_BLUE	1
#define RGB_LED_CONNECTION__BLUE_GREEN_RED	2
#define RGB_LED_CONNECTION					RGB_LED_CONNECTION__RED_GREEN_BLUE


/*********** CTL LED ***********/
#define UC_LED_DDR			DDRD
#define UC_LED_PORT			PORTD
#define UC_LED_PIN			PD4
#define TEST1_LED_DDR		DDRD
#define TEST1_LED_PORT		PORTD
#define TEST1_LED_PIN		PD6
#define TEST2_LED_DDR		DDRD
#define TEST2_LED_PORT		PORTD
#define TEST2_LED_PIN		PD7
#define TEST3_LED_DDR		DDRA
#define TEST3_LED_PORT		PORTA
#define TEST3_LED_PIN		PA7
#define IRMP_LED_DDR		TEST1_LED_DDR
#define IRMP_LED_PORT		TEST1_LED_PORT
#define IRMP_LED_PIN		TEST1_LED_PIN
#define RUNTIME_LED_DDR 	TEST2_LED_DDR
#define RUNTIME_LED_PORT 	TEST2_LED_PORT
#define RUNTIME_LED_PIN		TEST2_LED_PIN
#define RUNTIME_OSC_DDR 	TEST3_LED_DDR
#define RUNTIME_OSC_PORT 	TEST3_LED_PORT
#define RUNTIME_OSC_PIN		TEST3_LED_PIN


/********* BUTTONS ********/
#define BUTTON_OFF_DDR		DDRB
#define BUTTON_OFF_PORT		PINB
#define BUTTON_OFF_PIN		BUTTON_INVALID
#define BUTTON_MODE_DDR		DDRB
#define BUTTON_MODE_PORT	PINB
#define BUTTON_MODE_PIN		PB1
#define BUTTON_FUNC1_DDR	DDRB
#define BUTTON_FUNC1_PORT	PINB
#define BUTTON_FUNC1_PIN	BUTTON_INVALID
#define BUTTON_FUNC2_DDR	DDRB
#define BUTTON_FUNC2_PORT	PINB
#define BUTTON_FUNC2_PIN	BUTTON_INVALID
#define BUTTON_FUNC3_DDR	DDRB
#define BUTTON_FUNC3_PORT	PINB
#define BUTTON_FUNC3_PIN	BUTTON_INVALID
#define BUTTON_LEFT_DDR		DDRB
#define BUTTON_LEFT_PORT	PINB
#define BUTTON_LEFT_PIN		BUTTON_INVALID
#define BUTTON_RIGHT_DDR	DDRB
#define BUTTON_RIGHT_PORT	PINB
#define BUTTON_RIGHT_PIN	BUTTON_INVALID
#define BUTTON_UP_DDR		DDRB
#define BUTTON_UP_PORT		PINB
#define BUTTON_UP_PIN		BUTTON_INVALID
#define BUTTON_DOWN_DDR		DDRB
#define BUTTON_DOWN_PORT	PINB
#define BUTTON_DOWN_PIN		BUTTON_INVALID


/********** USART *********/

#define USART_REQESTER_MODE			0x40
#define USART_REQESTER_BUTTON		0x30
#define USART_REQESTER_COLOR		0x10
#define USART_REQESTER_CLOCK		0x80

#define USART_DATA_LENGTH_MODE		1
#define USART_DATA_LENGTH_BUTTON	2
#define USART_DATA_LENGTH_COLOR		4
#define USART_DATA_LENGTH_CLOCK		8
#define USART_DATA_LENGTH_READ_MAX	4


/********** IRMP **********/
#define IRMP_REMOTE_ADDRESS		0xF708
#define IRMP_BUTTON_OFF			0x001B
#define IRMP_BUTTON_MODE		0x0004
#define IRMP_BUTTON_FUNC1		0x001F
#define IRMP_BUTTON_FUNC2		0x001E
#define IRMP_BUTTON_FUNC3		0x001A
#define IRMP_BUTTON_UP			0x0005
#define IRMP_BUTTON_DOWN		0x0000
#define IRMP_BUTTON_LEFT		0x0008
#define IRMP_BUTTON_RIGHT		0x0001

#endif


#if (PROJECT == PROJECT__LED_FRAME)

/*********** WS2801 ***********/
#define WS2801_NB		(LED_MATRIX_SIZE_COL * LED_MATRIX_SIZE_LIN)
#define RGB_LED_CONNECTION__RED_GREEN_BLUE	1
#define RGB_LED_CONNECTION__BLUE_GREEN_RED	2
#define RGB_LED_CONNECTION					RGB_LED_CONNECTION__RED_GREEN_BLUE


/*********** CTL LED ***********/
#define UC_LED_DDR			DDRD
#define UC_LED_PORT			PORTD
#define UC_LED_PIN			PD4
#define TEST1_LED_DDR		DDRD
#define TEST1_LED_PORT		PORTD
#define TEST1_LED_PIN		PD6
#define TEST2_LED_DDR		DDRD
#define TEST2_LED_PORT		PORTD
#define TEST2_LED_PIN		PD7
#define TEST3_LED_DDR		DDRA
#define TEST3_LED_PORT		PORTA
#define TEST3_LED_PIN		PA7
#define IRMP_LED_DDR		TEST1_LED_DDR
#define IRMP_LED_PORT		TEST1_LED_PORT
#define IRMP_LED_PIN		TEST1_LED_PIN
#define RUNTIME_LED_DDR 	TEST2_LED_DDR
#define RUNTIME_LED_PORT 	TEST2_LED_PORT
#define RUNTIME_LED_PIN		TEST2_LED_PIN
#define RUNTIME_OSC_DDR 	TEST3_LED_DDR
#define RUNTIME_OSC_PORT 	TEST3_LED_PORT
#define RUNTIME_OSC_PIN		TEST3_LED_PIN


/********** USART *********/

#define USART_REQESTER_MODE			0x40
#define USART_REQESTER_BUTTON		0x30
#define USART_REQESTER_COLOR		0x10
#define USART_REQESTER_CLOCK		0x80

#define USART_DATA_LENGTH_MODE		1
#define USART_DATA_LENGTH_BUTTON	2
#define USART_DATA_LENGTH_COLOR		4
#define USART_DATA_LENGTH_CLOCK		8
#define USART_DATA_LENGTH_READ_MAX	4


/********** IRMP **********/
#define IRMP_REMOTE_ADDRESS		0xF708
#define IRMP_BUTTON_OFF			0x001B
#define IRMP_BUTTON_MODE		0x0004
#define IRMP_BUTTON_FUNC1		0x001F
#define IRMP_BUTTON_FUNC2		0x001E
#define IRMP_BUTTON_FUNC3		0x001A
#define IRMP_BUTTON_UP			0x0005
#define IRMP_BUTTON_DOWN		0x0000
#define IRMP_BUTTON_LEFT		0x0008
#define IRMP_BUTTON_RIGHT		0x0001

#endif

/* SPI SPEED */
#define SPI_CLK_DIV_16			1
#define SPI_CLK_DIV_8			2
#define SPI_DISABLED			255

#ifdef WS2801_NB
#if (WS2801_NB < 100)
#define SPI_SPEED SPI_CLK_DIV_8
#else
#define SPI_SPEED SPI_CLK_DIV_16
#endif
#endif

#endif /* DRIVERS_CONFIG_H_ */
